<a href="https://colab.research.google.com/github/solharsh/ML_Repository_University_Of_Chicago_PGD/blob/master/Neural_Netword_Keras_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Pre-processing

In [0]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
df = pd.read_csv('/content/drive/My Drive/AI DL JIGSAW/diabetes.csv')

In [0]:
df.head(1)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1

[1 rows x 9 columns]

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


No Null values

In [0]:
df.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [0]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
# X will contain all the Independent variables such as pregnancies, glucose, bloodpressure, skin thickness, insulin, bmi, diabetes pedigree function, and age
# y haas the outcomes i.e. the Dependent variable

In [0]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [0]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Neural Network (NN)

In [0]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential # sequential module reqd to initialize the NN
from keras.layers import Dense # dense module reqd to build the layers of the NN

Using TensorFlow backend.


In [0]:
# Initialising the ANN
diabetes_predictor = Sequential() 
# creating object of Sequential class

In [0]:
X.shape

(768, 8)

In [0]:
# Adding the input layer and the hidden layer
diabetes_predictor.add(Dense(input_dim=X.shape[1], activation="relu", kernel_initializer="uniform", units=5))
# add method of object classifier to add layers
# Dense function will take care of the first step of ANN i.e. randomly intializing weights of synapses to small number close to 0 (but not 0); done with init = 'uniform' (initialize weights based on uniform distribution)
# 8 input nodes we know from our dataset; hence input_dim = 8
# Forward-propagation by applying the activiation function. Neuron applies the activation fn to the sum of weights*inputs. The closer the activation fn value is to 1, the more activated the neuron, and the more activated the neuron, the more it passes on the signal
# Use rectifier activation fn for hiddern layers; activation = 'relu'
# units i.e the output dimensions is set = 6 which is the chosen number of nodes in this hidden layer
# TIP: no rule of thumb to choosing ouput dimensions; can choose average of the number of nodes in the input layer and the number of nodes in the output layer

In [0]:
# Adding the output layer
diabetes_predictor.add(Dense(activation = 'sigmoid', kernel_initializer = "uniform", units = 1))
# sigmoid activation fn for the output layer

In [0]:
# Compiling the ANN
diabetes_predictor.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# optimizer is the algo used to find the optimal no of weights in the NN (until now weights have only been initialized); 'adam' is a type of SGD algo
# loss deals with the loss function within the SGD algo which needs to be optimized(minimized); loss fn for SGD gong to be the same as that for logistic regression (logarithmic loss); since sigmoid fn used as activation fn we use log loss fn
# acuracy metric ensure that accuracy increases batch by batch; metrics parameter expecting a list so 'accuracy' added in []

In [0]:
# Fitting the ANN to the Training set
diabetes_predictor.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)
# Weights upated via batch learning so batch size needs to be specified (no rule of thumb)
# when the whole training set is passed throught the ANN, that makes an epoch. Epoch size needs to be specified (no rule of thumb)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
614/614 [==============================] - 0s 602us/step - loss: 0.6898 - accuracy: 0.6091
Epoch 2/100
614/614 [==============================] - 0s 104us/step - loss: 0.6772 - accuracy: 0.6433
Epoch 3/100
614/614 [==============================] - 0s 120us/step - loss: 0.6513 - accuracy: 0.7068
Epoch 4/100
614/614 [==============================] - 0s 115us/step - loss: 0.6146 - accuracy: 0.7541
Epoch 5/100
614/614 [==============================] - 0s 125us/step - loss: 0.5766 - accuracy: 0.7671
Epoch 6/100
614/614 [==============================] - 0s 122us/step - loss: 0.5468 - accuracy: 0.7606
Epoch 7/100
614/614 [==============================] - 0s 117us/step - loss: 0.5251 - accuracy: 0.7606
Epoch 8/100
614/614 [==============================] - 0s 119us/step - loss: 0.5105 - accuracy: 0.7655
Epoch 9/100
614/614 [==============================] - 0s 96us/step - loss: 0.5000 - accuracy: 0.7704
Epoch 10/100
614/614 [==============================] - 0s 98us/step - los

# Making the predictions and evaluating the model

In [0]:
# Predicting the Test set results
y_pred = diabetes_predictor.predict(X_test)
# this gives us the probability of a patient having diabetes
y_pred = (y_pred > 0.5)
# this above syntax is equivalent to sayig if y_pred>0.5 give value 1 and if not give value 0

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[94, 13],
       [19, 28]])