In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\solharsh\Desktop\Data Science\Machine Learning\Jigsaw\RNN and LSTM\Preclass Codes-2\69. Working with Embedding Layers in Keras\stack-overflow-data.csv")

In [3]:
data.head()

post         tags
0  what is causing this behavior  in our c# datet...           c#
1  have dynamic html load as if it was in an ifra...      asp.net
2  how to convert a float value in to min:sec  i ...  objective-c
3  .net framework 4 redistributable  just wonderi...         .net
4  trying to calculate and print the mean and its...       python

In [4]:
X=data['post']
Y=data['tags']

In [5]:
X.head()

0    what is causing this behavior  in our c# datet...
1    have dynamic html load as if it was in an ifra...
2    how to convert a float value in to min:sec  i ...
3    .net framework 4 redistributable  just wonderi...
4    trying to calculate and print the mean and its...
Name: post, dtype: object

In [6]:
Y.head()

0             c#
1        asp.net
2    objective-c
3           .net
4         python
Name: tags, dtype: object

In [7]:
Y.unique()

array(['c#', 'asp.net', 'objective-c', '.net', 'python', 'angularjs',
       'iphone', 'ruby-on-rails', 'ios', 'c', 'sql', 'java', 'jquery',
       'css', 'c++', 'php', 'android', 'mysql', 'javascript', 'html'],
      dtype=object)

In [15]:
import sklearn.feature_extraction.text as text

In [16]:
from sklearn.model_selection import train_test_split

In [66]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.10,random_state=200)

In [67]:
X_train.head()

21805    is there an library to support nsdictionary tr...
25783    replacing fileinputstream with getresourceasst...
34843    how to email the current screen of ios app in ...
16332    how to create the nscalender and gregorian cal...
32383    is it possible to check what the client is sen...
Name: post, dtype: object

In [68]:
#TFIDF Representation

In [69]:
tfidf = text.TfidfVectorizer(input=X_train.tolist(),stop_words='english',max_features=1000,ngram_range=(1,1))

In [70]:
X_train = tfidf.fit_transform(X_train.tolist())

In [71]:
X_test = tfidf.transform(X_test.tolist())

In [72]:
X_train.shape

(36000, 1000)

In [73]:
X_test.shape

(4000, 1000)

In [74]:
Y.head()

0             c#
1        asp.net
2    objective-c
3           .net
4         python
Name: tags, dtype: object

In [75]:
#Need to convert these tags to integer representation and then do a one hot encoding

In [76]:
from sklearn.preprocessing import LabelEncoder

In [77]:
enc = LabelEncoder()

In [78]:
enc.fit(data['tags'])

LabelEncoder()

In [79]:
Y_train = enc.transform(Y_train)

In [80]:
Y_test = enc.transform(Y_test)

In [81]:
Y_train

array([15, 11, 15, ...,  5,  3, 18])

In [82]:
enc.classes_ #to understand encoding

array(['.net', 'android', 'angularjs', 'asp.net', 'c', 'c#', 'c++', 'css',
       'html', 'ios', 'iphone', 'java', 'javascript', 'jquery', 'mysql',
       'objective-c', 'php', 'python', 'ruby-on-rails', 'sql'],
      dtype=object)

In [83]:
from keras.models import Sequential

In [84]:
from keras.layers import Dense,Dropout

In [85]:
from keras.utils import to_categorical #create one hot encoded version

In [86]:
Y_train = to_categorical(Y_train)

In [87]:
Y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [88]:
model = Sequential()

In [89]:
model.add(Dense(512,input_shape=(1000,),activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(20,activation='softmax'))

In [90]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

In [92]:
model.fit(X_train,Y_train,epochs=10,batch_size=32,verbose=1,validation_split=0.10)

Train on 32400 samples, validate on 3600 samples
Epoch 1/10
32400/32400 [==============================] - 36s 1ms/step - loss: 0.5549 - accuracy: 0.8219 - val_loss: 0.6324 - val_accuracy: 0.8039
Epoch 2/10
32400/32400 [==============================] - 32s 984us/step - loss: 0.5043 - accuracy: 0.8344 - val_loss: 0.6309 - val_accuracy: 0.8053
Epoch 3/10
32400/32400 [==============================] - 19s 588us/step - loss: 0.4661 - accuracy: 0.8475 - val_loss: 0.6400 - val_accuracy: 0.8014
Epoch 4/10
32400/32400 [==============================] - 19s 582us/step - loss: 0.4265 - accuracy: 0.8595 - val_loss: 0.6457 - val_accuracy: 0.8025
Epoch 5/10
32400/32400 [==============================] - 26s 810us/step - loss: 0.3918 - accuracy: 0.8705 - val_loss: 0.6598 - val_accuracy: 0.8017
Epoch 6/10
32400/32400 [==============================] - 46s 1ms/step - loss: 0.3579 - accuracy: 0.8801 - val_loss: 0.6651 - val_accuracy: 0.8031
Epoch 7/10
32400/32400 [==============================] - 26s

In [93]:
#We got the occuracy of 92% with validation accuraty of 79.7%

In [94]:
#A sample question from stack overflow. We will be predicting the class of this question

q='''

I am new to luigi, came across it while designing a pipeline for our ML efforts and though it wasn't fitted to my particular use case it had so many extra features I decided to fit it to my use case, basically what I was looking for was a way to be able to persist a custom built pipeline and thus have its result repeatable, after reading most of the online tutorials I tried to implement my serialization using the existing luigi.cfg configuration and command line mechanisms and it might have sufficed for the tasks' parameters but it provided no way of serializing the DAG connectivity of my pipeline, so I decided to have a WrapperTask which received a json config file which would create all the task instances and connect all the plumbing. I hereby enclose a small test program for your scrutiny:

import random
import luigi
import time
import os


class TaskNode(luigi.Task):
    i = luigi.IntParameter()  # node ID

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.required = []

    def set_required(self, required=None):
        self.required = required  # set the dependencies
        return self

    def requires(self):
        return self.required

    def output(self):
        return luigi.LocalTarget('{0}{1}.txt'.format(self.__class__.__name__, self.i))

    def run(self):
        with self.output().open('w') as outfile:
            outfile.write('inside {0}{1}\n'.format(self.__class__.__name__, self.i))
        self.process()

    def process(self):
        raise NotImplementedError(self.__class__.__name__ + " must implement this method")


class FastNode(TaskNode):

    def process(self):
        time.sleep(1)


class SlowNode(TaskNode):

    def process(self):
        time.sleep(2)


# This WrapperTask builds all the nodes 
class All(luigi.WrapperTask):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        num_nodes = 513

        classes = TaskNode.__subclasses__()
        self.nodes = []
        for i in reversed(range(num_nodes)):
            cls = random.choice(classes)

            dependencies = random.sample(self.nodes, (num_nodes - i) // 35)

            obj = cls(i=i)
            if dependencies:
                obj.set_required(required=dependencies)
            else:
                obj.set_required(required=None)

            # delete existing output causing a build all
            if obj.output().exists():
                obj.output().remove()  

            self.nodes.append(obj)

    def requires(self):
        return self.nodes


if __name__ == '__main__':
    luigi.run()
So, basically, as states in the question title, this focuses on the dynamic dependencies and generates a 513 node dependency DAG with p=1/35 connectivity probability, it also makes the All WrapperTask class require all nodes (I have a version which only connects it to heads of connected DAG components but I didn't want to over complicate).

Is there a more standard way of implementing this? Especially note the not so pretty complication with the TaskNode init and set_required methods, I only did it this way because receiving parameters in the init method clashes somehow with the way luigi registers parameters. I also tried several other ways but this was basically the most decent one (that worked)

If there isn't a standard way I'd still love to hear any insights you have on the way I plan to go before I implement the entire piping framework.'''

In [95]:
q_v=tfidf.transform([q])

In [100]:
model.predict_classes(q_v)

array([17], dtype=int64)

In [101]:
#we got the prediction to be class 17. Let's see what class 17 is

In [103]:
enc.inverse_transform([17])

array(['python'], dtype=object)

In [105]:
#The model correctly classified the question to be of class python. Hurray!!

In [106]:
z='''
I'm trying to start a fragment programmatically. The function below works fine on its own. The problem here is, that I have to call the function from within another fragment. The call from the fragment to MainActivity works and is not the problem.

public void gotoFragment1(){
    Fragment1 fragment = new Fragment1();
    FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
    transaction.replace(R.id.nav_host_fragment, fragment);
    transaction.addToBackStack(null);
    transaction.commit();
}
If I try to call the function from another fragment the app crashes with the following stacktrace:

java.lang.IllegalStateException: FragmentManager has not been attached to a host.
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1727)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
    at com.fewo.info.MainActivity.gotoVeranstaltungen(MainActivity.java:134)
    at com.fewo.info.ui.home.HomeFragment$1.onClick(HomeFragment.java:53)
How can I change the fragment with this code beeing called from within another fragment?'''

In [107]:
z_v=tfidf.transform([z])

In [108]:
model.predict_classes(z_v)

array([11], dtype=int64)

In [110]:
enc.inverse_transform([11])

array(['java'], dtype=object)